### ISSUE TITLE
[Request] Auto-closing within the period

### ISSUE THREAD

**Issue by spywhere** [webArtisan/lessTabs#2]
Auto closing old tabs automatically would be a good feature. Since, I don't have to mind pressing shortcut key in order to close the tabs. :D

**Comment by avinash8526** [comment]
If unused tabs are closed when even you open a new file will it meet your requirement ? As per the functionality people may or may not want to close unused tabs, hence to bind closing of tabs with new file command will be a good idea. As soon as you open new file all unused tabs will be closed, but yes this should be configurable as not every one wants this functionality.

**Comment by spywhere** [comment]
Close unused tabs on open is good. But I usually works with a projects so I could end up to many tabs at once. But I see your point that some people don't want to close unused tabs...

To summarize, I would depends on your choice. If you implements it, I use it. If not, I would stick to the old one. :\

Edit:
I just misunderstand your comment :( My bad

**Comment by avinash8526** [comment]
Ok, I will implement it and send a pull request to this repository, you can expect this by Thursday IST 2300 hrs

**Comment by webArtisan** [comment]
The feature (on a new tab is opened -> close) has been implemented.
